version: '3.7'
services:
  sorc3r3r-dockerized-actions-runner-01:
    image: docker.pkg.github.com/sorc3r3r/dockerized-actions-runner/dockerized-actions-runner:latest
    network_mode: host
    privileged: true
    environment:
      - "RUNNER_NAME=-dockerized-actions-runner-01"
      - "RUNNER_REPOSITORY_URL=https://github.com/sorc3r3r/dockerized-actions-runner"
      - "GITHUB_ACCESS_TOKEN=TOKEN_01"
      - "RUNNER_WORK_DIRECTORY=_work"
      - "RUNNER_LABELS=dockerized"
    command: bash -c "./runner.sh"
  sorc3r3r-dockerized-actions-runner-02:
    image: docker.pkg.github.com/sorc3r3r/dockerized-actions-runner/dockerized-actions-runner:latest
    network_mode: host
    privileged: true
    environment:
      - "RUNNER_NAME=-dockerized-actions-runner-02"
      - "RUNNER_REPOSITORY_URL=https://github.com/sorc3r3r/dockerized-actions-runner"
      - "GITHUB_ACCESS_TOKEN=TOKEN_02"
      - "RUNNER_WORK_DIRECTORY=_work"
      - "RUNNER_LABELS=dockerized"
    command: bash -c "./runner.sh"
